services:
  db:
    image: pgvector/pgvector:pg16
    container_name: ia_vector_db
    environment:
      POSTGRES_USER: usuario_ia
      POSTGRES_PASSWORD: password_seguro
      POSTGRES_DB: ia_database
    ports:
      - "5432:5432"
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql # <--- CAMBIO AQUÍ
      - pgdata:/var/lib/postgresql/data

  backend: # Antes se llamaba 'app'
    build: ./backend # <--- CAMBIO AQUÍ (Apunta a la carpeta)
    container_name: ia_brain_backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://usuario_ia:password_seguro@db:5432/ia_database
      - HF_API_KEY=${HF_API_KEY}
    depends_on:
      - db
    command: npm run dev
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  pgdata: